In [1]:
import pandas as pd
import numpy as np


In [3]:
!nvidia-smi

Wed Oct 16 21:27:44 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   51C    P8              8W /   40W |      12MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
print(torch.__version__)

2.4.1+cu124


## Types of tensor

In [ ]:
# 1) scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# find out the dimension
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# 2) vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 6]])
MATRIX

tensor([[7, 8],
        [9, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([9, 6])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[30, 222, 3020, 7], [47778, 53333, 6010101, 0], [700000000, 22222222228, 1212121229, 4]]])
TENSOR

tensor([[[         30,         222,        3020,           7],
         [      47778,       53333,     6010101,           0],
         [  700000000, 22222222228,  1212121229,           4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 4])

### Random tensors

Why random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# create of random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.7216, 0.5188, 0.7951, 0.6610],
        [0.1248, 0.5590, 0.1652, 0.3410],
        [0.9834, 0.8095, 0.0741, 0.6101]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
rand_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, colour channel
rand_image_size_tensor.shape, rand_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
torch.rand(3, 3)

tensor([[0.8355, 0.8015, 0.4410],
        [0.9710, 0.9591, 0.9633],
        [0.9261, 0.1334, 0.6468]])

In [ ]:
# create tensor of all zeros
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
ones.ndim

2

In [ ]:
ones.shape

torch.Size([3, 4])

### Create a range of tensors and tensors-like

In [ ]:
# use torch.range()
one_to_ten = torch.arange(0, 30, step=4)
one_to_ten

tensor([ 0,  4,  8, 12, 16, 20, 24, 28])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0])

### tensor dtypes

**note :** tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning :
1. tensors not right dtype
2. tensors not right shape
3. tensors not on the right device

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g float32 pf float 16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_nyoba = float_32_tensor.type(torch.float16)
float_16_nyoba

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_nyoba / float_32_tensor

tensor([1., 1., 1.])

In [ ]:
nyoba_int = torch.tensor([1, 45, 955], dtype=torch.int)
nyoba_int

tensor([  1,  45, 955], dtype=torch.int32)

In [ ]:
float_biasa_lagi = torch.tensor([99, 8, 71], dtype=torch.long)
float_biasa_lagi

tensor([99,  8, 71])

In [ ]:
nyoba_int * float_biasa_lagi


tensor([   99,   360, 67805])

### Getting informations from tensor (tensor aattributes)

1. tensors not right dtype - to get dtype from a tensor use `tensor.dtype`
2. tensors not right shape - to get to know shape from a tensor use `tensor.shape`
3. tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# bikin tensor nge tes
tensor_baru = torch.rand([3, 5])
tensor_baru

tensor([[0.6230, 0.8227, 0.3704, 0.0792, 0.5368],
        [0.5944, 0.0258, 0.3276, 0.7403, 0.7103],
        [0.6458, 0.8445, 0.0757, 0.4714, 0.2519]])

In [ ]:
# detail tentang itu
print(tensor_baru)
print(f"Datatype of tensor : {tensor_baru.dtype}")
print(f"Shape of tensor : {tensor_baru.size()}")
print(f"Device tensor is on : {tensor_baru.device}")

tensor([[0.6230, 0.8227, 0.3704, 0.0792, 0.5368],
        [0.5944, 0.0258, 0.3276, 0.7403, 0.7103],
        [0.6458, 0.8445, 0.0757, 0.4714, 0.2519]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 5])
Device tensor is on : cpu


In [ ]:
tensor_lagi = torch.tensor([1, 2, 3], dtype=torch.long)
tensor_lagi.dtype

torch.int64

In [ ]:
twnsor_baru_jadi_int = tensor_lagi.type(torch.short)
twnsor_baru_jadi_int

tensor([1, 2, 3], dtype=torch.int16)

### Manipulating tensors (tensor operations)

Tensor operations include :
- Addition
- Substraction
- Multiplication (element wise)
- Division
- Matrix multipication

In [ ]:
# create a tensor and add 10 to it
tensor_nyoba_lagi = torch.tensor([1, 3, 5])
tensor_nyoba_lagi + 10

tensor([11, 13, 15])

In [ ]:
# Multiply tensor by 10
tensor_nyoba_lagi * 10

tensor([10, 30, 50])

In [ ]:
tensor_nyoba_lagi

tensor([1, 3, 5])

In [ ]:
# Substraction
tensor_nyoba_lagi - 10

tensor([-9, -7, -5])

In [ ]:
# try out pytorch in-bulit function
torch.mul(tensor_nyoba_lagi, 10)

tensor([10, 30, 50])

In [ ]:
torch.add(tensor_nyoba_lagi, 9)

tensor([10, 12, 14])

### Matrix multipication

2 main ways of performing multiplication in nueral networks and deep learning
- Element wise multiplication
- Matrix Multiplication (dot ptoduct)

more info on multiplication matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

there are 2 rules that performing matrix multplication needs to satisfy:
1. the **inner dimensions** must match:
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. the resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)`-> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`



In [ ]:
# element wise multiplicatiin
print(tensor_nyoba_lagi, "*", tensor_nyoba_lagi)
print(f"Equals : {tensor_nyoba_lagi * tensor_nyoba_lagi}")

tensor([1, 3, 5]) * tensor([1, 3, 5])
Equals : tensor([ 1,  9, 25])


In [ ]:
# matrix multiplication
torch.matmul(tensor_nyoba_lagi, tensor_nyoba_lagi)

tensor(35)

In [ ]:
tensor_nyoba_lagi

tensor([1, 3, 5])

In [ ]:
# matrix multiplication by hand
1*1 + 3*3 + 5*5

35

In [ ]:
%%time
value = 0
for i in range(len(tensor_nyoba_lagi)):
    value += tensor_nyoba_lagi[i] * tensor_nyoba_lagi[i]
print(value)

tensor(35)
CPU times: user 1.7 ms, sys: 0 ns, total: 1.7 ms
Wall time: 1.61 ms


In [ ]:
%%time
torch.matmul(tensor_nyoba_lagi, tensor_nyoba_lagi)
#

CPU times: user 38 µs, sys: 7 µs, total: 45 µs
Wall time: 47.9 µs


tensor(35)

### one of the most common errors in deep learning : shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_a = torch.tensor([[1, 2],
                      [3, 4],
                      [5, 6]])

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_a, tensor_b) # torch.mm = torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor issues, we can manitpulate the shape one of our tensors using a transpose

a **transpose** switches the axis or dimensions of a given tensor

In [ ]:
tensor_b.T, tensor_b.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_b, tensor_b.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# the matrix multiplication operations works when tensor tensor_B is transposed
print(f"Original shapes : tensor_a = {tensor_a.shape}, tensor_b = {tensor_b.shape}")
print(f"New shapes : tensor_a = {tensor_a.shape} (same as above), tensor_b.T = {tensor_b.T.shape}")
print(f"Multiplying : {tensor_a.shape} @ {tensor_b.T.shape} <- inner dimensions must match")
print("Output : \n")
output = torch.mm(tensor_a, tensor_b.T)
print(output)
print(f"\nOutput shape : {output.shape}")

torch.mm(tensor_a, tensor_b.T).shape

Original shapes : tensor_a = torch.Size([3, 2]), tensor_b = torch.Size([3, 2])
New shapes : tensor_a = torch.Size([3, 2]) (same as above), tensor_b.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output : 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape : torch.Size([3, 3])


torch.Size([3, 3])

In [ ]:
tensor_c = torch.tensor([[10, 30],
                         [40, 60],
                         [70, 90]])

tensor_d = torch.tensor([[25, 15],
                         [85, 35],
                         [75, 5]])

torch.mm(tensor_c, tensor_d)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_c.shape, tensor_d.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_c.T

tensor([[10, 40, 70],
        [30, 60, 90]])

In [ ]:
# when tried to Transpose one of them (tensor_c)
print(f"Original shapes : tensor_c = {tensor_c.shape}, tensor_d = {tensor_d.shape}")
print(f"New shapes : tensor_c.T = {tensor_c.T.shape} (same as above), tensor_d = {tensor_d.shape}")
print(f"Multiplying : {tensor_c.T.shape} @ {tensor_d.shape} <- inner dimensions must match")
print("Output : \n")
output = torch.mm(tensor_c.T, tensor_d)
print(output)
print(f"\nOutput shape : {output.shape}")

torch.mm(tensor_c.T, tensor_d).shape

Original shapes : tensor_c = torch.Size([3, 2]), tensor_d = torch.Size([3, 2])
New shapes : tensor_c.T = torch.Size([2, 3]) (same as above), tensor_d = torch.Size([3, 2])
Multiplying : torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimensions must match
Output : 

tensor([[ 8900,  1900],
        [12600,  3000]])

Output shape : torch.Size([2, 2])


torch.Size([2, 2])

## tensor aggregation, finding min, max, mean, sum, etc


In [ ]:
# create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# find the minimum value
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# find the max value
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the max value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Rehsaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshaping an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# let's create a tensor
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
y_reshaped = y.reshape(1, 9)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = y.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
y_stacked = torch.stack([y, y, y, y], dim=0)
y_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
a = torch.arange(1, 5)
a
b = torch.arange(1, 5)


In [ ]:
b

tensor([1, 2, 3, 4])

In [ ]:
c = torch.hstack([a, b])
c

tensor([1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
d = torch.vstack([a, b])
d

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [ ]:
# try torch.squeeze()
y_reshaped.shape

torch.Size([1, 9])

In [ ]:
y_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
y_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
y_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
y_tersqueeeze = y_reshaped.squeeze()

In [ ]:
y_tersqueeeze

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# torch unsqueeze - adds a single dimension to target tensor at a spesific dim
print(f"Previous target : {y_tersqueeeze}")
print(f"Previous shape : {y_tersqueeeze.shape}")

# Add an extra dimension with unsqueeze
y_unsqueezed = y_tersqueeeze.unsqueeze(dim=1)
print(f"\nNew tensor : {y_unsqueezed}")
print(f"New shape : {y_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New tensor : tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape : torch.Size([9, 1])


In [ ]:
# torch permute - rearranges the dimensions of a target tensor in a spesified order
x_ori = torch.rand(size=(224, 224, 3)) # height, width, colour_channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_ori.permute(2, 0, 1) # shifts axis 0-> 1, 1->2, 2-> 0

In [ ]:
print(f"Previous shape : {x_ori.shape}")
print(f"New shape : {x_permuted.shape}") # [colors channels, height, width]

Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [ ]:
x_ori[0, 0, 0] = 728218
x_ori[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

### Indexing (selecting data from tensors with indexing)

INdexing with pytorch is similar to indexing with numpy

In [ ]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][1][2]

tensor(6)

In [ ]:
# lets index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
# lets index on the most inner vracket (last dimension)
x[0][1][0]

tensor(4)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# u can use ":" to select "all" off a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th and 1st dim but only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of the dim but only the 1 index value 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dim and all values off 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[0, 1, :]

tensor([4, 5, 6])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

## Pytorch tensors and numpy

Numpy is a populare sicentific python numerical computing library. and because of this, pytorch has fuctionality to interact with it.

* Data in numpy, want in pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
#numpy array to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning when cnverting from from numpy -> pytorch, p[ytorch reflects numpy's default data ty[e of float 64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
np.arange(1.0, 8.0).dtype

dtype('float64')

In [ ]:
#Change the value of array, what will this do to `tensor`?
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

in short how how nn learns :
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

to reduce the randomness in nn and pytorch comes the concept of a random seed. Essentially what the random seed does is "flavor" the randomness.

In [ ]:
import torch

# create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8407, 0.9758, 0.0167, 0.7631],
        [0.0599, 0.9191, 0.4887, 0.3844],
        [0.4240, 0.0803, 0.5759, 0.1396]])
tensor([[0.7555, 0.3745, 0.0703, 0.4372],
        [0.9548, 0.5997, 0.8706, 0.1472],
        [0.8391, 0.0706, 0.5498, 0.4487]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

import torch

# set the random sed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
# torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility :
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster compututations)

GPUs = faster computation on numbers, thanks to CUD + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

## 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options... see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

for 2 & 3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to pytorch setup documentation : https://pytorch.org/get-started/locally/

### 2. Check for GPU access with pytorch

For pytorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnosic code : https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code

E.g run on gpu if available, else default to GPU

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# setup devie agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

the reasons we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# create a tensor (default on the GPU)0
tensorrr = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensorrr, tensorrr.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to gpu if available
tensor_on_gpu = tensorrr.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the cpu


In [ ]:
#iif tensor cant transform it to numpy
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [ ]:
# to fix the gpu with numpt issue, we can first set it to the cpu
tensor_getting_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_getting_back_to_cpu

array([1, 2, 3])

### Exercises & Extra-curriculum : https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [ ]:
latihan = torch.rand(7, 7)
latihan

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [ ]:
latihan2 = torch.rand(1, 7)
latihan2

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036]])

In [ ]:
perkalian = torch.matmul(latihan, latihan2.T)
perkalian

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [ ]:
perkalian

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [ ]:
torch.manual_seed(1234)

In [ ]:
random3 = torch.rand(2, 3, device='cuda')
random3

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

In [ ]:
random4 = torch.rand(2,3 , device='cuda')
random4

tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')

In [ ]:
hasil34 = torch.mm(random3, random4.T)
hasil34

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

In [ ]:
print(hasil34.max())
print(hasil34.min())

tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


In [ ]:
print(hasil34.argmax())
print(hasil34.argmin())

tensor(1, device='cuda:0')
tensor(0, device='cuda:0')


In [ ]:
random5 = torch.rand(1, 1, 1, 10)
random5

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [ ]:
torch.manual_seed(7)

sq1 = random5.squeeze()
sq2 = sq1.squeeze()
sq3 = sq2.squeeze()
sq3

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

In [ ]:
print(sq3[0])
print(sq3[0].shape)

print(sq3[1])
print(sq3[1].shape)



tensor(0.5349)
torch.Size([])
tensor(0.1988)
torch.Size([])
